name: Code Quality
on:
  push:
    branches: [ master, main, update ]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - ["3.10", "3.11", "3.12"]
        poetry-version: ["1.8.3"]
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/my-custom-path
          installer-parallel: true

      - name: Install Packages
        run: |
          poetry install -v

      - name: Lint
        run: |
          poetry run make lint

      - name: Tests
        run: |
          poetry run make tests

      - name: Doc Tests
        run: |
          make test-docs
