on:
  push:
    branches: [ master, main, update ]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-versions: ["3.10", "3.11", "3.12"]
        poetry-version: ["1.8.3"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{github.token}}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/my-custom-path
          installer-parallel: true

      - name: Install Packages
        run: |
          poetry install -v

      - name: Lint
        run: |
          poetry run make lint

      - name: Tests
        run: |
          poetry run make tests

      - name: Doc Tests
        run: |
          make test-docs
