on:
  pull_request:
    types:
      - opened
    branches: [ master, main, update ]
    paths:
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  check_deps:
    name: Check dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ["3.10", "3.11", "3.12"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{github.token}}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install ci dependencies
        run: |
          make are_deps_dirty && exit 0
          python -m pip install --upgrade pip
          pip install poetry tox-gh-actions tox-poetry

      - name: Install application deps
        run: |
          make are_deps_dirty && exit 0
          poetry install

      - name: Lock application deps
        run: |
          make are_deps_dirty || poetry lock
          echo "No change in dependencies not locking."
