on:
  pull_request:
    types:
      - opened
    branches: [ master, main, update ]
    paths:
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  check_deps:
    name: Check dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{github.token}}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          token: ${{github.token}}

      - name: install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: install project
        run: |
          uv venv .venv -p ${{matrix.python-version}}
          source .venv/bin/activate
          uv pip install -e .[all]

      - name: Install application deps
        run: |
          source .venv/bin/activate
          make are_deps_dirty && exit 0
          poetry install

      - name: Lock application deps
        run: |
          source .venv/bin/activate
          make are_deps_dirty || poetry lock
          echo "No change in dependencies not locking."
