name: Dependency Workflows
on:
  pull_request:
    types:
      - opened
    branches: [ master, main, update ]
    paths:
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  check_deps:
    strategy:
      matrix:
        python-versions:
          - ["3.10", "3.11", "3.12"]
        os:
        - ubuntu-24.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install ci dependencies
        run: |
          make are_deps_dirty && exit 0
          python -m pip install --upgrade pip
          pip install poetry tox-gh-actions tox-poetry

      - name: Install application deps
        run: |
          make are_deps_dirty && exit 0
          poetry install

      - name: Lock application deps
        run: |
          make are_deps_dirty || poetry lock
          echo "No change in dependencies not locking."
