# Publish package on main branch if it's tagged with 'v*'

name: release & publish workflow

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
permissions:
  id-token: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-versions: [3.10.4]

    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      - uses: actions/checkout@v2
      - uses: BobAnkh/add-contributors@master
        with:
          CONTRIBUTOR: '### Contributors'
          COLUMN_PER_ROW: '3'
          ACCESS_TOKEN: ${{secrets.GH_TOKEN}}
          IMG_WIDTH: '100'
          FONT_SIZE: '14'
          PATH: '/README.md'
          COMMIT_MESSAGE: 'docs(README): update contributors'
          AVATAR_SHAPE: 'round'

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build wheels and source tarball
        run: >-
          poetry build

      - name: create github release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          body: ${{ steps.changelog_reader.outputs.changes }}
          files: dist/*.whl
          draft: false
          prerelease: false
      
      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
